spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mbti_test?useSSL=false&serverTimezone=UTC
    username: your_db_username
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 开发环境使用，生产环境改为 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: adminpass
      roles: ADMIN
  cache:
    type: caffeine # 启用缓存

# JWT 配置（可选）
jwt:
  secret: mbtiSecretKey123!@#
  expiration: 86400000 # 24小时